### ISSUE TITLE
Crashes on git failure

### ISSUE THREAD

**Issue by freman** [jonasmalacofilho/git-cache-http-server#11]
Not entirely sure as to the mechanism behind the failure but it became unusable overnight which made me frowny face

```
Oct 20 20:27:54 river env[28229]: git-upload-pack done with exit 0
Oct 20 20:27:54 river env[28229]: POST /github.com/hashicorp/golang-lru/git-upload-pack
Oct 20 20:27:54 river env[28229]: authenticating on the upstream repo
Oct 20 20:27:54 river env[28229]: updating: fetch failed, cloning
Oct 20 20:27:54 river env[28229]: /usr/lib/node_modules/git-cache-http-server/bin/git-cache-http-server.js:91
Oct 20 20:27:54 river env[28229]:                                         throw new js__$Boot_HaxeError("git clone exited with non-zero status: " + cerr.code);
Oct 20 20:27:54 river env[28229]:                                         ^
Oct 20 20:27:54 river env[28229]: Error: git clone exited with non-zero status: 128
Oct 20 20:27:54 river env[28229]:     at /usr/lib/node_modules/git-cache-http-server/bin/git-cache-http-server.js:91:12
Oct 20 20:27:54 river env[28229]:     at ChildProcess.exithandler (child_process.js:278:5)
Oct 20 20:27:54 river env[28229]:     at emitTwo (events.js:125:13)
Oct 20 20:27:54 river env[28229]:     at ChildProcess.emit (events.js:213:7)
Oct 20 20:27:54 river env[28229]:     at maybeClose (internal/child_process.js:927:16)
Oct 20 20:27:54 river env[28229]:     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
Oct 20 20:27:56 river systemd[1]: git-cache-http-server.service: Main process exited, code=exited, status=1/FAILURE
Oct 20 20:27:56 river systemd[1]: git-cache-http-server.service: Unit entered failed state.
Oct 20 20:27:56 river systemd[1]: git-cache-http-server.service: Failed with result 'exit-code'.
Oct 20 22:00:01 river systemd[1]: Started Caching git http server.
```

Simply restarting it fixed it

**Comment by jonasmalacofilho** [comment]
Github experienced increased error rates this evening.

---

Additionally, you can check out #9 for increased logging of git errors and #8 for what's planned in terms of more resilience to fetch errors.

**Comment by jonasmalacofilho** [comment]
See also: https://status.github.com
